// Code generated by const_generator.go; DO NOT EDIT.
package constants

// User facing name of the operand application
const AppName = "Cryostat"

// Version of the Cryostat Operator
const OperatorVersion = "4.0.2-dev"

// Default image tag for the OAuth2 Proxy
const DefaultOAuth2ProxyImageTag = "quay.io/oauth2-proxy/oauth2-proxy:latest"

// Default image tag for the OpenShift OAuth Proxy
const DefaultOpenShiftOAuthProxyImageTag = "quay.io/cryostat/openshift-oauth-proxy:4.0"

// Default image tag for the core application image
const DefaultCoreImageTag = "quay.io/cryostat/cryostat:4.0.2-snapshot"

// Default image tag for the JFR datasource image
const DefaultDatasourceImageTag = "quay.io/cryostat/jfr-datasource:4.0.2-snapshot"

// Default image tag for the Grafana dashboard image
const DefaultGrafanaImageTag = "quay.io/cryostat/cryostat-grafana-dashboard:4.0"

// Default image tag for the Grafana dashboard image
const DefaultReportsImageTag = "quay.io/cryostat/cryostat-reports:4.0.2-snapshot"

// Default image tag for the Storage image
const DefaultStorageImageTag = "quay.io/cryostat/cryostat-storage:4.0"

// Default image tag for the Database image
const DefaultDatabaseImageTag = "quay.io/cryostat/cryostat-db:4.0"

// Default image tag for the agent proxy image
const DefaultAgentProxyImageTag = "registry.access.redhat.com/ubi9/nginx-124:latest"

// Default image tag for the agent init container image
const DefaultAgentInitImageTag = "quay.io/cryostat/cryostat-agent-init:0.5.2-snapshot"
