apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cryostat-plugin
    app.kubernetes.io/instance: cryostat-plugin
    app.kubernetes.io/name: cryostat-plugin
    app.kubernetes.io/part-of: cryostat-plugin
  name: cryostat-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cryostat-plugin
subjects:
- kind: ServiceAccount
  name: cryostat-plugin
  namespace: plugin--cryostat-plugin
