apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  labels:
    app: cryostat-plugin
    app.kubernetes.io/instance: cryostat-plugin
    app.kubernetes.io/name: cryostat-plugin
    app.kubernetes.io/part-of: cryostat-plugin
  name: cryostat-plugin
spec:
  backend:
    service:
      basePath: /
      name: cryostat-plugin
      namespace: plugin--cryostat-plugin
      port: 9443
    type: Service
  displayName: cryostat-plugin Plugin
  i18n:
    loadType: Preload
  proxy:
  - alias: cryostat-plugin-proxy
    authorization: UserToken
    endpoint:
      service:
        name: cryostat-plugin
        namespace: plugin--cryostat-plugin
        port: 9443
      type: Service
