apiVersion: v1
imagePullSecrets:
- name: cryostat-plugin-dockercfg-w8glf
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: cryostat-plugin-dockercfg-w8glf
  labels:
    app: cryostat-plugin
    app.kubernetes.io/instance: cryostat-plugin
    app.kubernetes.io/name: cryostat-plugin
    app.kubernetes.io/part-of: cryostat-plugin
  name: cryostat-plugin
  namespace: plugin--cryostat-plugin
secrets:
- name: cryostat-plugin-dockercfg-w8glf
