apiVersion: v1
imagePullSecrets:
- name: cryostat-plugin-dockercfg-w8glf
kind: ServiceAccount
metadata:
  labels:
    app: cryostat-plugin
    app.kubernetes.io/instance: cryostat-plugin
    app.kubernetes.io/name: cryostat-plugin
    app.kubernetes.io/part-of: cryostat-plugin
  name: cryostat-plugin
  namespace: system
