pull_request_rules:
  - name: backport patches to v1 branch
    conditions:
      - base=main
      - label=backport
    actions:
      backport:
        branches:
          - v1
        assignees:
          - "{{ author }}"
