---
scorecard:
    output: text
    namespace: scorecard
    crds-dir: "deploy/crds"
    plugins:
        # TODO add test configurations for FlightRecorders
        - basic:
            cr-manifest:
                - "deploy/crds/rhjmc.redhat.com_v1alpha1_containerjfr_cr.yaml"
        - olm:
            cr-manifest:
                - "deploy/crds/rhjmc.redhat.com_v1alpha1_containerjfr_cr.yaml"
            csv-path: "bundle/container-jfr-operator.v0.2.1.clusterserviceversion.yaml"
