---
# TODO automatically update bundle/CSV version number
scorecard:
    output: text
    bundle: "deploy/olm-catalog/container-jfr-operator-bundle"
    plugins:
        - basic:
            crds-dir: "deploy/crds"
            cr-manifest:
                - "deploy/crds/rhjmc.redhat.com_v1alpha1_containerjfr_cr.yaml"
                - "deploy/crds/rhjmc.redhat.com_v1alpha2_flightrecorder_cr.yaml"
                - "deploy/crds/rhjmc.redhat.com_v1alpha2_recording_cr.yaml"
        - olm:
            crds-dir: "deploy/crds"
            cr-manifest:
                - "deploy/crds/rhjmc.redhat.com_v1alpha1_containerjfr_cr.yaml"
                - "deploy/crds/rhjmc.redhat.com_v1alpha2_flightrecorder_cr.yaml"
                - "deploy/crds/rhjmc.redhat.com_v1alpha2_recording_cr.yaml"
            csv-path: "deploy/olm-catalog/container-jfr-operator-bundle/0.5.0/container-jfr-operator-bundle.v0.5.0.clusterserviceversion.yaml"
