---
scorecard:
    output: text
    namespace: scorecard
    crds-dir: "deploy/crds"
    plugins:
        # TODO add test configurations for FlightRecorders
        - basic:
            cr-manifest:
                - "deploy/crds/rhjmc.redhat.com_v1alpha1_containerjfr_cr.yaml"
                - "deploy/crds/rhjmc.redhat.com_v1alpha1_flightrecorder_cr.yaml"
        - olm:
            cr-manifest:
                - "deploy/crds/rhjmc.redhat.com_v1alpha1_containerjfr_cr.yaml"
                - "deploy/crds/rhjmc.redhat.com_v1alpha1_flightrecorder_cr.yaml"
            # TODO automatically update version number
            csv-path: "deploy/olm-catalog/container-jfr-operator-bundle/0.3.0/container-jfr-operator-bundle.v0.3.0.clusterserviceversion.yaml"
