apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

# patches:
# - path: patches/force_openshift_patch.yaml
#   target:
#     group: apps
#     kind: Deployment
#     name: controller
#     namespace: system
#     version: v1

images:
- name: controller
  newName: quay.io/cryostat/cryostat-operator
  newTag: 4.2.0-dev
