apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

# patches:
# - path: patches/force_openshift_patch.yaml
#   target:
#     group: apps
#     kind: Deployment
#     name: controller
#     namespace: system
#     version: v1

images:
- name: controller
  newName: quay.io/cryostat/cryostat-operator
  newTag: 4.3.0-dev@sha256:f2ea231c29febf716a052c1318e8a5d2ea8c6b8ffc466e6b2649754f19709404
