---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryostat-operator.fullname" . }}-controller-manager-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryostat-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "cryostat-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryostat-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryostat-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cryostat-operator
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    {{- include "cryostat-operator.selectorLabels" . | nindent 4 }}
