---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "cryostat-operator.fullname" . }}-mutating-webhook-configuration
  labels:
    {{- include "cryostat-operator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "cryostat-operator.fullname" . }}-service-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle:
    service:
      name: {{ include "cryostat-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-operator-cryostat-io-v1beta2-cryostat
  failurePolicy: Fail
  name: mcryostat.kb.io
  rules:
  - apiGroups:
    - operator.cryostat.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - cryostats
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "cryostat-operator.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "cryostat-operator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "cryostat-operator.fullname" . }}-service-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle:
    service:
      name: {{ include "cryostat-operatort.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-operator-cryostat-io-v1beta2-cryostat
  failurePolicy: Fail
  name: vcryostat.kb.io
  rules:
  - apiGroups:
    - operator.cryostat.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - cryostats
  sideEffects: None