// Code generated by imagetag_generator.go; DO NOT EDIT.
package resource_definitions

// Default image tag for the core application image
const DefaultCoreImageTag = "quay.io/cryostat/cryostat:latest"

// Default image tag for the JFR datasource image
const DefaultDatasourceImageTag = "quay.io/cryostat/jfr-datasource:latest"

// Default image tag for the Grafana dashboard image
const DefaultGrafanaImageTag = "quay.io/cryostat/cryostat-grafana-dashboard:latest"

// Default image tag for the Grafana dashboard image
const DefaultReportsImageTag = "quay.io/cryostat/cryostat-reports:latest"
