// Code generated by imagetag_generator.go; DO NOT EDIT.
package resource_definitions

// Default image tag for the core application image
const DefaultCoreImageTag = "quay.io/cryostat/cryostat:2.0.0-SNAPSHOT"

// Default image tag for the JFR datasource image
const DefaultDatasourceImageTag = "quay.io/cryostat/jfr-datasource:1.0.0"

// Default image tag for the Grafana dashboard image
const DefaultGrafanaImageTag = "quay.io/cryostat/cryostat-grafana-dashboard:1.0.0"
