# Modifies operator deployment to use Insights integration
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: INSIGHTS_ENABLED
    value: "true"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: INSIGHTS_URL
    value: "http://insights-proxy.$(OPERATOR_NAMESPACE).svc.cluster.local:8080"
