resources:
- ../openshift
- ../../insights


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: insights_manager_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: controller
    namespace: system
    version: v1
- path: insights_patch.yaml
