- op: add
  path: /serviceaccount
  value: cryostat-scorecard
- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - cryostat-scorecard-tests
    - operator-install
    image: "quay.io/cryostat/cryostat-operator-scorecard:2.3.0-20221116195419"
    labels:
      suite: cryostat
      test: operator-install
