FROM docker.io/grafana/grafana:7.2.1

EXPOSE 3000

RUN grafana-cli plugins install grafana-simple-json-datasource

COPY --chown=grafana:grafana \
	dashboards.yaml \
	dashboard.json \
	/etc/grafana/provisioning/dashboards

COPY --chown=grafana:grafana \
    datasource.yaml.in \
    /tmp/

# Listen address of jfr-datasource
ENV JFR_DATASOURCE_URL "http://0.0.0.0:8080"

USER root
COPY cjfr-run.sh /usr/bin/

USER grafana
ENTRYPOINT [ "/usr/bin/cjfr-run.sh" ]
