FROM docker.io/grafana/grafana:7.2.1

EXPOSE 3000

RUN grafana-cli plugins install grafana-simple-json-datasource

COPY --chown=grafana:grafana \
	dashboards.yaml \
	dashboard.json \
	/etc/grafana/provisioning/dashboards
