// Code generated by imagetag_generator.go; DO NOT EDIT.
package resource_definitions

// Default image tag for the core application image
const DefaultCoreImageTag = "quay.io/cryostatio/cryostat:1.0.0-BETA6"

// Default image tag for the JFR datasource image
const DefaultDatasourceImageTag = "quay.io/cryostatio/jfr-datasource:1.0.0-BETA6"

// Default image tag for the Grafana dashboard image
const DefaultGrafanaImageTag = "quay.io/cryostatio/cryostat-grafana-dashboard:1.0.0-BETA3"
