apiVersion: v1
data:
  CORE_IMG: quay.io/rh-jmc-team/container-jfr:1.0.0-BETA6
  DATASOURCE_IMG: quay.io/rh-jmc-team/jfr-datasource:1.0.0-BETA6
  GRAFANA_IMG: quay.io/rh-jmc-team/container-jfr-grafana-dashboard:1.0.0-BETA3
kind: ConfigMap
metadata:
  name: container-jfr-operator-manager-env
