// Code generated by const_generator.go; DO NOT EDIT.
package controllers

// User facing name of the operand application
const AppName = "Cryostat"

// Version of the Cryostat Operator
const OperatorVersion = "2.5.0-dev"

// Default image tag for the core application image
const DefaultCoreImageTag = "quay.io/cryostat/cryostat:2.4.0-snapshot"

// Default image tag for the JFR datasource image
const DefaultDatasourceImageTag = "quay.io/cryostat/jfr-datasource:2.4.0-snapshot"

// Default image tag for the Grafana dashboard image
const DefaultGrafanaImageTag = "quay.io/cryostat/cryostat-grafana-dashboard:cryostat-v2.4"

// Default image tag for the Grafana dashboard image
const DefaultReportsImageTag = "quay.io/cryostat/cryostat-reports:2.4.0-snapshot"
