apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: container-jfr-operator-cluster-role
rules:
- apiGroups:
  - console.openshift.io
  resources:
  - consolelinks
  verbs:
  - get
  - create
  - list
  - update
  - delete
