# permissions for end users to view clustercryostats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustercryostat-viewer-role
rules:
- apiGroups:
  - operator.cryostat.io
  resources:
  - clustercryostats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.cryostat.io
  resources:
  - clustercryostats/status
  verbs:
  - get
