# permissions for end users to edit clustercryostats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustercryostat-editor-role
rules:
- apiGroups:
  - operator.cryostat.io
  resources:
  - clustercryostats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.cryostat.io
  resources:
  - clustercryostats/status
  verbs:
  - get
