---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-role-binding
  labels:
    app: containerjfr
subjects:
- kind: ServiceAccount
  name: service-account
roleRef:
  kind: ClusterRole
  name: role
  apiGroup: rbac.authorization.k8s.io
