# permissions for end users to edit containerjfrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerjfr-editor-role
rules:
- apiGroups:
  - rhjmc.redhat.com
  resources:
  - containerjfrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rhjmc.redhat.com
  resources:
  - containerjfrs/status
  verbs:
  - get
