# Namespaced Cryostat permissions to be bound by RoleBindings
# in each target namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cryostat-namespaced
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - pods
      - replicationcontrollers
  - verbs:
      - get
    apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
      - daemonsets
      - statefulsets
  - verbs:
      - get
    apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
  - verbs:
      - get
      - list
    apiGroups:
      - route.openshift.io
    resources:
      - routes
