# permissions for end users to edit cryostats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cryostat-editor-role
rules:
- apiGroups:
  - operator.cryostat.io
  resources:
  - cryostats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.cryostat.io
  resources:
  - cryostats/status
  verbs:
  - get
