# permissions for end users to view cryostats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cryostat-viewer-role
rules:
- apiGroups:
  - operator.cryostat.io
  resources:
  - cryostats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.cryostat.io
  resources:
  - cryostats/status
  verbs:
  - get
