# permissions for end users to edit flightrecorders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flightrecorder-editor-role
rules:
- apiGroups:
  - operator.cryostat.io
  resources:
  - flightrecorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.cryostat.io
  resources:
  - flightrecorders/status
  verbs:
  - get
