# permissions for end users to edit recordings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recording-editor-role
rules:
- apiGroups:
  - operator.cryostat.io
  resources:
  - recordings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.cryostat.io
  resources:
  - recordings/status
  verbs:
  - get
