# permissions for end users to view recordings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recording-viewer-role
rules:
- apiGroups:
  - operator.cryostat.io
  resources:
  - recordings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.cryostat.io
  resources:
  - recordings/status
  verbs:
  - get
