apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: flightrecorders.rhjmc.redhat.com
spec:
  group: rhjmc.redhat.com
  names:
    kind: FlightRecorder
    listKind: FlightRecorderList
    plural: flightrecorders
    singular: flightrecorder
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            recordingActive:
              description: Specifies whether a JFR recording should be started or
                stopped
              type: boolean
          required:
          - recordingActive
          type: object
        status:
          properties:
            recordingActive:
              description: Whether the pod/service is currently recording
              type: boolean
            recordings:
              description: Lists all recordings for the pod/service that may be downloaded
              items:
                type: string
              type: array
            target:
              description: Reference to the pod/service that this object controls
                JFR for
              type: object
          required:
          - target
          - recordingActive
          - recordings
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
