apiVersion: rhjmc.redhat.com/v1alpha2
kind: Recording
metadata:
  name: example-recording
spec:
  name: example-recording
  eventOptions: [ ALL ]
  duration: 30s
  archive: true
  flightRecorder:
    name: example-flightrecorder
