apiVersion: rhjmc.redhat.com/v1beta1
kind: ContainerJFR
metadata:
  name: containerjfr
spec:
  minimal: false
  trustedCertSecrets: []
  storageOptions:
    pvc:
      labels: {}
      annotations: {}
      spec: {}
