apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "rhjmc.redhat.com/v1beta1",
          "kind": "ContainerJFR",
          "metadata": {
            "name": "containerjfr"
          },
          "spec": {
            "minimal": false,
            "trustedCertSecrets": []
          }
        },
        {
          "apiVersion": "rhjmc.redhat.com/v1beta1",
          "kind": "FlightRecorder",
          "metadata": {
            "name": "example-flightrecorder"
          },
          "spec": {
            "recordingSelector": {
              "matchLabels": {
                "rhjmc.redhat.com/flightrecorder": "example-flightrecorder"
              }
            }
          }
        },
        {
          "apiVersion": "rhjmc.redhat.com/v1beta1",
          "kind": "Recording",
          "metadata": {
            "name": "example-recording"
          },
          "spec": {
            "archive": true,
            "duration": "30s",
            "eventOptions": [
              "template=ALL"
            ],
            "flightRecorder": {
              "name": "example-flightrecorder"
            },
            "name": "example-recording"
          }
        }
      ]
    capabilities: Basic Install
    categories: Monitoring, Developer Tools
    certified: "false"
    containerImage: quay.io/rh-jmc-team/container-jfr-operator:1.0.0-beta5
    createdAt: "2020-07-03 00:00:00"
    description: JVM monitoring and profiling tool
    operators.operatorframework.io/builder: operator-sdk-v1.5.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: github.com/rh-jmc-team/container-jfr-operator
    support: Red Hat
  name: container-jfr-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ContainerJFR is the Schema for the containerjfrs API
      displayName: Container JFR
      kind: ContainerJFR
      name: containerjfrs.rhjmc.redhat.com
      version: v1beta1
    - description: FlightRecorder is the Schema for the flightrecorders API
      displayName: Flight Recorder
      kind: FlightRecorder
      name: flightrecorders.rhjmc.redhat.com
      version: v1beta1
    - description: Recording is the Schema for the recordings API
      displayName: Recording
      kind: Recording
      name: recordings.rhjmc.redhat.com
      version: v1beta1
  description: |
    ContainerJFR provides a cloud-based solution for interacting with the JDK Flight Recorder already present in OpenJDK 11+ JVMs. With ContainerJFR, users can remotely start, stop, retrieve, and even analyze JFR event data, providing the capbility to easily take advantage of Flight Recorder''s extremely low runtime cost and overhead and the flexibility to monitor applications and analyze recording data without transferring data outside of the cluster the application runs within.
  displayName: ContainerJFR
  icon:
  - base64data: ""
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - flightrecorder
  - java
  - jdk
  - jfr
  - jmc
  - missioncontrol
  - monitoring
  - profiling
  links:
  - name: Upstream Project
    url: https://github.com/rh-jmc-team/container-jfr
  maintainers:
  - email: aazores@redhat.com
    name: Andrew Azores
  - email: ebaron@redhat.com
    name: Elliott Baron
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 1.0.0-beta5
