apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: container-jfr-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ContainerJFR is the Schema for the containerjfrs API
      displayName: Container JFR
      kind: ContainerJFR
      name: containerjfrs.rhjmc.redhat.com
      version: v1beta1
    - description: FlightRecorder is the Schema for the flightrecorders API
      displayName: Flight Recorder
      kind: FlightRecorder
      name: flightrecorders.rhjmc.redhat.com
      version: v1beta1
    - description: Recording is the Schema for the recordings API
      displayName: Recording
      kind: Recording
      name: recordings.rhjmc.redhat.com
      version: v1beta1
  description: Some description text
  displayName: ContainerJFR Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - jfr
  - jdk
  links:
  - name: Container Jfr Operator
    url: https://container-jfr-operator.domain
  maintainers:
  - email: aazores@redhat.com
    name: Andrew Azores
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 0.0.0
