apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.cryostat.io/v1beta1",
          "kind": "Cryostat",
          "metadata": {
            "name": "cryostat"
          },
          "spec": {
            "minimal": false,
            "trustedCertSecrets": []
          }
        },
        {
          "apiVersion": "operator.cryostat.io/v1beta1",
          "kind": "FlightRecorder",
          "metadata": {
            "name": "example-flightrecorder"
          },
          "spec": {
            "recordingSelector": {
              "matchLabels": {
                "operator.cryostat.io/flightrecorder": "example-flightrecorder"
              }
            }
          }
        },
        {
          "apiVersion": "operator.cryostat.io/v1beta1",
          "kind": "Recording",
          "metadata": {
            "name": "example-recording"
          },
          "spec": {
            "archive": true,
            "duration": "30s",
            "eventOptions": [
              "template=ALL"
            ],
            "flightRecorder": {
              "name": "example-flightrecorder"
            },
            "name": "example-recording"
          }
        }
      ]
    capabilities: Basic Install
    categories: Monitoring, Developer Tools
    containerImage: quay.io/cryostat/cryostat-operator:2.1.0-dev
    createdAt: "2021-04-30 00:00:00"
    description: JVM monitoring and profiling tool
    operators.operatorframework.io/builder: operator-sdk-v1.5.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: github.com/cryostatio/cryostat-operator
    support: Cryostat Community
  name: cryostat-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Cryostat contains configuration options for controlling the Deployment of the Cryostat application and its related components. A Cryostat instance must be created to instruct the operator to deploy the Cryostat application.
      displayName: Cryostat
      kind: Cryostat
      name: cryostats.operator.cryostat.io
      resources:
      - kind: ConsoleLink
        name: ""
        version: v1
      - kind: Deployment
        name: ""
        version: v1
      - kind: Ingress
        name: ""
        version: v1
      - kind: PersistentVolumeClaim
        name: ""
        version: v1
      - kind: Route
        name: ""
        version: v1
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      specDescriptors:
      - description: Use cert-manager to secure in-cluster communication between Cryostat components. Requires cert-manager to be installed.
        displayName: Enable cert-manager Integration
        path: enableCertManager
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: List of Flight Recorder Event Templates to preconfigure in Cryostat
        displayName: Event Templates
        path: eventTemplates
      - description: Name of config map in the local namespace
        displayName: Config Map Name
        path: eventTemplates[0].configMapName
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:ConfigMap
      - description: Deploy a pared-down Cryostat instance with no Grafana dashboard or jfr-datasource and no web-client UI.
        displayName: Minimal Deployment
        path: minimal
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Options to customize the storage for Flight Recordings and Templates
        displayName: Storage Options
        path: storageOptions
      - description: Configuration for the Persistent Volume Claim to be created by the operator.
        displayName: PVC
        path: storageOptions.pvc
      - description: Spec for a Persistent Volume Claim, whose options will override the defaults used by the operator. Unless overriden, the PVC will be created with the default Storage Class and 500MiB of storage. Once the operator has created the PVC, changes to this field have no effect.
        displayName: Spec
        path: storageOptions.pvc.spec
      - description: List of TLS certificates to trust when connecting to targets
        displayName: Trusted TLS Certificates
        path: trustedCertSecrets
      - description: Name of secret in the local namespace
        displayName: Secret Name
        path: trustedCertSecrets[0].secretName
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      statusDescriptors:
      - displayName: Application URL
        path: applicationUrl
        x-descriptors:
        - urn:alm:descriptor:org.w3:link
      version: v1beta1
    - description: FlightRecorder represents a target Pod that is capable of creating JDK Flight Recordings using Cryostat. The Cryostat operator creates FlightRecorder objects when it finds compatible Pods.
      displayName: Flight Recorder
      kind: FlightRecorder
      name: flightrecorders.operator.cryostat.io
      resources:
      - kind: Pod
        name: ""
        version: v1
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      specDescriptors:
      - description: If JMX authentication is enabled for this FlightRecorder's JVM, specify the credentials in a secret and reference it here
        displayName: JMXCredentials
        path: jmxCredentials
      - description: Recordings that match this selector belong to this FlightRecorder
        displayName: Recording Selector
        path: recordingSelector
      statusDescriptors:
      - description: Listing of events available in the target JVM
        displayName: Events
        path: events
      - description: JMX port for target JVM
        displayName: Port
        path: port
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Reference to the pod/service that this object controls JFR for
        displayName: Target
        path: target
      - description: Listing of templates available in the target JVM
        displayName: Templates
        path: templates
      version: v1beta1
    - description: Recording represents a JDK Flight Recording. Create a Recording object to instruct Cryostat to start a new recording for a Pod. An alternative to managing recordings with the Cryostat web application.
      displayName: Recording
      kind: Recording
      name: recordings.operator.cryostat.io
      resources:
      - kind: Pod
        name: ""
        version: v1
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      specDescriptors:
      - description: Whether this recording should be saved to persistent storage. If true, the JFR file will be retained until this object is deleted. If false, the JFR file will be deleted when its corresponding JVM exits.
        displayName: Archive
        path: archive
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:checkbox
      - description: The requested total duration of the recording, a zero value will record indefinitely. The duration format is a combination of hours (h), minutes (m) and seconds (s). e.g. 30s, 0s, 1h30m
        displayName: Duration
        path: duration
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Name of the event template to use when creating the recording. Must be prefixed with "template=". e.g. template=Profiling
        displayName: Event Template
        path: eventOptions
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Reference to the FlightRecorder object that corresponds to this Recording. Select the FlightRecorder with the name of the target Pod for this Recording.
        displayName: Flight Recorder
        path: flightRecorder
      - description: Name of the recording to be created.
        displayName: Name
        path: name
      - description: Desired state of the recording. If omitted, RUNNING will be assumed.
        displayName: State
        path: state
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:RUNNING
        - urn:alm:descriptor:com.tectonic.ui:select:STOPPED
      statusDescriptors:
      - description: A URL to download the JFR file for the recording.
        displayName: Download URL
        path: downloadURL
        x-descriptors:
        - urn:alm:descriptor:org.w3:link
      - description: The duration of the recording specified during creation.
        displayName: Duration
        path: duration
        x-descriptors:
        - urn:alm:descriptor:text
      - description: A URL to download the autogenerated HTML report for the recording
        displayName: Report URL
        path: reportURL
        x-descriptors:
        - urn:alm:descriptor:org.w3:link
      - description: The date/time when the recording started.
        displayName: Start Time
        path: startTime
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Current state of the recording.
        displayName: State
        path: state
        x-descriptors:
        - urn:alm:descriptor:text
      version: v1beta1
  description: |
    Cryostat provides a cloud-based solution for interacting with the JDK Flight Recorder already present in OpenJDK 11+ JVMs. With Cryostat, users can remotely start, stop, retrieve, and even analyze JFR event data, providing the capbility to easily take advantage of Flight Recorder's extremely low runtime cost and overhead and the flexibility to monitor applications and analyze recording data without transferring data outside of the cluster the application runs within.
  displayName: Cryostat
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - flightrecorder
  - java
  - jdk
  - jfr
  - jmc
  - missioncontrol
  - monitoring
  - profiling
  - diagnostic
  links:
  - name: Upstream Project
    url: https://github.com/cryostatio/cryostat
  maintainers:
  - email: cryostat-development@googlegroups.com
    name: The Cryostat Authors
  maturity: stable
  provider:
    name: The Cryostat Community
  version: 2.1.0-dev
