apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: container-jfr-operator
rules:
- apiGroups:
  - console.openshift.io
  resources:
  - consolelinks
  verbs:
  - '*'
