---
apiVersion: rbac.authorization.k8s.io/v1
kind: List
metadata: {}
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: exposecontroller
    subjects:
    - kind: ServiceAccount
      name: exposecontroller
    roleRef:
      kind: Role
      name: exposecontroller
      apiGroup: rbac.authorization.k8s.io
  # TODO replace these clusterrolebindings with narrower set of permissions
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: exposecontroller-cluster-admin
    subjects:
    - kind: ServiceAccount
      name: exposecontroller
      namespace: default
    roleRef:
      kind: ClusterRole
      name: cluster-admin
      apigroup: rbac.authorization.k8s.io
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: serviceaccounts-cluster-reader
    subjects:
    - kind: Group
      name: system:serviceaccounts
    roleRef:
      kind: ClusterRole
      name: cluster-reader
      apigroup: rbac.authorization.k8s.io
