---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: exposecontroller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - routes
  - routes.route.openshift.io
  - endpoints
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
