---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-jfr-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: container-jfr-operator
  template:
    metadata:
      labels:
        name: container-jfr-operator
    spec:
      serviceAccountName: container-jfr-operator
      containers:
        - name: container-jfr-operator
          image: quay.io/rh-jmc-team/container-jfr-operator:0.4.0
          command:
          - container-jfr-operator
          imagePullPolicy: Always
          env:
            - name: TLS_VERIFY
              value: 'true'
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: container-jfr-operator
