apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: containerjfr
  name: container-jfr-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
