apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: containerjfr
  name: container-jfr-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: container-jfr-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: container-jfr-operator-system
