apiVersion: operator.cryostat.io/v1beta2
kind: Cryostat
metadata:
  name: cryostat-sample
spec:
  enableCertManager: true
  enableAudit: true
  trustedCertSecrets: []
  eventTemplates: []
  reportOptions:
    replicas: 0
  networkPolicies: {}
  storageOptions:
    scratch:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
      cachePercentage: 50
