---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus-test
  name: quarkus-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-test
  template:
    metadata:
      labels:
        app: quarkus-test
    spec:
      containers:
        - image: quay.io/redhat-java-monitoring/quarkus-cryostat-agent:latest
          imagePullPolicy: Always
          name: quarkus-test
          env:
            - name: JAVA_OPTS_APPEND
              value: -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dcom.sun.management.jmxremote.port=9097 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
            - name: QUARKUS_HTTP_HOST
              value: 0.0.0.0
          ports:
          - containerPort: 10010
            protocol: TCP
            name: app-http
          - containerPort: 9097
            protocol: TCP
            name: jfr-jmx
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          livenessProbe:
            httpGet:
              path: /hello-resteasy
              port: app-http
            initialDelaySeconds: 3
          readinessProbe:
            httpGet:
              path: /hello-resteasy
              port: app-http
            initialDelaySeconds: 3
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-test
  name: quarkus-test
spec:
  selector:
    app: quarkus-test
  ports:
  - name: jfr-jmx
    port: 9097
    protocol: TCP
    targetPort: 9097
  - name: app-http
    port: 10010
    protocol: TCP
    targetPort: 10010
