---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus-cryostat-agent-injected
  name: quarkus-cryostat-agent-injected
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-cryostat-agent-injected
  template:
    metadata:
      labels:
        app: quarkus-cryostat-agent-injected
        cryostat.io/name: cryostat-sample
        cryostat.io/namespace: cryostat-operator-system
    spec:
      containers:
      - env:
        - name: JAVA_OPTS_APPEND
          value: |-
            -Dquarkus.http.host=0.0.0.0
            -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            -Dio.cryostat.agent.shaded.org.slf4j.simpleLogger.defaultLogLevel=debug
        image: quay.io/redhat-java-monitoring/quarkus-cryostat-agent:latest
        imagePullPolicy: Always
        name: quarkus-cryostat-agent-injected
        ports:
        - containerPort: 10010
          protocol: TCP
          name: app-http
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /hello-resteasy
            port: app-http
          initialDelaySeconds: 3
        readinessProbe:
          httpGet:
            path: /hello-resteasy
            port: app-http
          initialDelaySeconds: 3
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-cryostat-agent-injected
  name: quarkus-cryostat-agent-injected
spec:
  selector:
    app: quarkus-cryostat-agent-injected
  ports:
  - name: app-http
    port: 10010
    protocol: TCP
    targetPort: 10010
