---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus-cryostat-agent
  name: quarkus-cryostat-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-cryostat-agent
  template:
    metadata:
      labels:
        app: quarkus-cryostat-agent
        cryostat.io/name: cryostat-sample
        cryostat.io/namespace: cryostat-operator-system
    spec:
      serviceAccountName: quarkus-cryostat-agent-serviceaccount
      containers:
      - env:
        - name: JAVA_OPTS_APPEND
          value: |-
            -Dquarkus.http.host=0.0.0.0
            -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            -Dio.cryostat.agent.shaded.org.slf4j.simpleLogger.defaultLogLevel=debug
        image: quay.io/redhat-java-monitoring/quarkus-cryostat-agent:latest
        imagePullPolicy: Always
        name: quarkus-cryostat-agent
        ports:
        - containerPort: 10010
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-cryostat-agent
  name: quarkus-cryostat-agent
spec:
  selector:
    app: quarkus-cryostat-agent
  ports:
  - name: agent-http
    port: 9977
    protocol: TCP
    targetPort: 9977
  - name: app-http
    port: 10010
    protocol: TCP
    targetPort: 10010
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: quarkus-cryostat-agent-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quarkus-cryostat-agent-role
rules:
- apiGroups:
  - ""
  verbs:
  - create
  resources:
  - pods/exec
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quarkus-cryostat-agent-role-binding
subjects:
- kind: ServiceAccount
  name: quarkus-cryostat-agent-serviceaccount
roleRef:
  kind: Role
  name: quarkus-cryostat-agent-role
  apiGroup: rbac.authorization.k8s.io
