---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus-cryostat-agent-tls-proxy
  name: quarkus-cryostat-agent-tls-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-cryostat-agent-tls-proxy
  template:
    metadata:
      labels:
        app: quarkus-cryostat-agent-tls-proxy
    spec:
      containers:
      - env:
        - name: CRYOSTAT_AGENT_APP_NAME
          value: agent-test
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CRYOSTAT_AGENT_API_WRITES_ENABLED
          value: "true"
        - name: CRYOSTAT_AGENT_BASEURI
          value: https://cryostat-sample-agent.$(NAMESPACE).svc:8282
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CRYOSTAT_AGENT_CALLBACK
          value: http://$(POD_IP):9977
        - name: JAVA_OPTS_APPEND
          value: |-
            -Dquarkus.http.host=0.0.0.0
            -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            -javaagent:/deployments/app/cryostat-agent.jar
            -Dcryostat.agent.webclient.tls.client-auth.cert.path=/var/run/secrets/io.cryostat/cryostat-agent/tls.crt
            -Dcryostat.agent.webclient.tls.client-auth.key.path=/var/run/secrets/io.cryostat/cryostat-agent/tls.key
            -Dcryostat.agent.webclient.tls.truststore.cert[0].path=/var/run/secrets/io.cryostat/cryostat-agent/ca.crt
            -Dcryostat.agent.webclient.tls.truststore.cert[0].type=X.509
            -Dcryostat.agent.webclient.tls.truststore.cert[0].alias=cryostat
        image: quay.io/redhat-java-monitoring/quarkus-cryostat-agent:latest
        imagePullPolicy: Always
        name: quarkus-cryostat-agent-tls-proxy
        ports:
        - containerPort: 10010
          protocol: TCP
        - containerPort: 9097
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/run/secrets/io.cryostat/cryostat-agent
          name: agent-tls
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
      volumes:
      - name: agent-tls
        secret:
          secretName: cryostat-agent-REPLACEHASH
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-cryostat-agent-tls-proxy
  name: quarkus-cryostat-agent-tls-proxy
spec:
  selector:
    app: quarkus-cryostat-agent-tls-proxy
  ports:
  - name: agent-http
    port: 9977
    protocol: TCP
    targetPort: 9977
  - name: app-http
    port: 10010
    protocol: TCP
    targetPort: 10010
