// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/rh-jmc-team/container-jfr-operator/pkg/apis/rhjmc/v1alpha1.FlightRecorder":       schema_pkg_apis_rhjmc_v1alpha1_FlightRecorder(ref),
		"github.com/rh-jmc-team/container-jfr-operator/pkg/apis/rhjmc/v1alpha1.FlightRecorderSpec":   schema_pkg_apis_rhjmc_v1alpha1_FlightRecorderSpec(ref),
		"github.com/rh-jmc-team/container-jfr-operator/pkg/apis/rhjmc/v1alpha1.FlightRecorderStatus": schema_pkg_apis_rhjmc_v1alpha1_FlightRecorderStatus(ref),
	}
}

func schema_pkg_apis_rhjmc_v1alpha1_FlightRecorder(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FlightRecorder is the Schema for the flightrecorders API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/rh-jmc-team/container-jfr-operator/pkg/apis/rhjmc/v1alpha1.FlightRecorderSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/rh-jmc-team/container-jfr-operator/pkg/apis/rhjmc/v1alpha1.FlightRecorderStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/rh-jmc-team/container-jfr-operator/pkg/apis/rhjmc/v1alpha1.FlightRecorderSpec", "github.com/rh-jmc-team/container-jfr-operator/pkg/apis/rhjmc/v1alpha1.FlightRecorderStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_rhjmc_v1alpha1_FlightRecorderSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FlightRecorderSpec defines the desired state of FlightRecorder",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_rhjmc_v1alpha1_FlightRecorderStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FlightRecorderStatus defines the observed state of FlightRecorder",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
