apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: container-jfr-operator-bundle.v0.0.7
  namespace: placeholder
  annotations:
    alm-examples: >-
      [
        {
          "apiVersion":"apiextensions.k8s.io/v1beta1",
          "kind":"ContainerJFR",
          "metadata":{
            "name":"containerjfr"
          },
          "spec":{}
        },
        {
          "apiVersion":"apiextensions.k8s.io/v1beta1",
          "kind":"FlightRecorder",
          "metadata":{
            "name":"flightrecorder"
          },
          "spec":{
            "recordingActive":false
          }
        }
      ]
    categories: 'Monitoring, Developer Tools'
    certified: 'false'
    createdAt: 2019-11-04T00:00:00Z
    description: JVM monitoring and profiling tool
    # TODO automatically replace the version tag
    containerImage: quay.io/rh-jmc-team/container-jfr-operator:0.1.7
    support: Red Hat
    capabilities: Basic Install
    repository: github.com/rh-jmc-team/container-jfr-operator
spec:
  displayName: ContainerJFR
  description: |
    ContainerJFR provides a cloud-based solution for interacting with the
    JDK Flight Recorder already present in OpenJDK 11+ JVMs. With ContainerJFR,
    users can remotely start, stop, retrieve, and even analyze JFR event data,
    providing the capbility to easily take advantage of Flight Recorder's
    extremely low runtime cost and overhead and the flexibility to monitor
    applications and analyze recording data without transferring data outside
    of the cluster the application runs within.
  maturity: pre-alpha
  version: 0.0.7
  replaces: ''
  minKubeVersion: ''
  keywords:
    - flightrecorder
    - java
    - jdk
    - jfr
    - jmc
    - missioncontrol
    - monitoring
    - profiling
  maintainers:
    - name: Andrew Azores
      email: aazores@redhat.com
    - Name: Elliott Baron
      email: ebaron@redhat.com
  provider:
    name: Red Hat
  labels: {}
  selector:
    matchLabels: {}
  links:
    - name: Upstream Project
      url: 'https://github.com/rh-jmc-team/container-jfr'
  icon:
    - base64data: ''
      mediatype: image/png
  customresourcedefinitions:
    owned:
      - name: containerjfrs.rhjmc.redhat.com
        displayName: ContainerJFR
        kind: ContainerJFR
        version: v1alpha1
        description: Container JFR
        resources:
          - version: v1
            kind: Deployment
          - version: v1
            kind: Service
          - version: v1
            kind: ReplicaSet
          - version: v1
            kind: Pod
          - version: v1
            kind: Secret
          - version: v1
            kind: ConfigMap
        specDescriptors: []
        statusDescriptors: []
      - name: flightrecorders.rhjmc.redhat.com
        displayName: FlightRecorder
        kind: FlightRecorder
        version: v1alpha1
        description: FlightRecorders
        resources:
          - version: v1
            kind: Deployment
          - version: v1
            kind: Service
          - version: v1
            kind: ReplicaSet
          - version: v1
            kind: Pod
          - version: v1
            kind: Secret
          - version: v1
            kind: ConfigMap
        specDescriptors: []
        statusDescriptors: []
    required: []
  install:
    strategy: deployment
    spec:
      # TODO copy in operator_role.yaml permissions rather than duplicating
      permissions:
        - serviceAccountName: container-jfr-operator
          rules:
            - apiGroups:
                - ''
              resources:
                - pods
                - services
                - services/finalizers
                - routes
                - routes.route.openshift.io
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - 'route.openshift.io'
              resources:
                - routes
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - apps
              resourceNames:
                - container-jfr-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - ''
              resources:
                - pods
              verbs:
                - get
            - apiGroups:
                - apps
              resources:
                - replicasets
              verbs:
                - get
            - apiGroups:
                - rhjmc.redhat.com
              resources:
                - '*'
              verbs:
                - '*'
      clusterPermissions: []
      deployments:
        - name: container-jfr-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: container-jfr-operator
            template:
              metadata:
                labels:
                  name: container-jfr-operator
              spec:
                serviceAccountName: container-jfr-operator
                containers:
                  - name: container-jfr-operator
                    image: 'quay.io/rh-jmc-team/container-jfr-operator:0.1.7'
                    command:
                      - container-jfr-operator
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: container-jfr-operator
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
