apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "rhjmc.redhat.com/v1alpha1",
          "kind": "ContainerJFR",
          "metadata": {
            "name": "containerjfr"
          },
          "spec": {
            "minimal": false
          }
        },
        {
          "apiVersion": "rhjmc.redhat.com/v1alpha1",
          "kind": "FlightRecorder",
          "metadata": {
            "name": "flightrecorder"
          },
          "spec": {
            "port": 9091,
            "recordingRequests": []
          }
        }
      ]
    capabilities: Basic Install
    categories: Monitoring, Developer Tools
    certified: 'false'
    containerImage: quay.io/rh-jmc-team/container-jfr-operator:0.3.0
    createdAt: 2019-11-04 00:00:00
    description: JVM monitoring and profiling tool
    repository: github.com/rh-jmc-team/container-jfr-operator
    support: Red Hat
  name: container-jfr-operator-bundle.v0.3.0
  namespace: placeholder
spec:
  customresourcedefinitions:
    owned:
    - description: Container JFR
      displayName: ContainerJFR
      kind: ContainerJFR
      name: containerjfrs.rhjmc.redhat.com
      resources:
      - kind: Deployment
        version: v1
      - kind: Service
        version: v1
      - kind: ReplicaSet
        version: v1
      - kind: Pod
        version: v1
      - kind: Secret
        version: v1
      - kind: ConfigMap
        version: v1
      specDescriptors: []
      statusDescriptors: []
      version: v1alpha1
    - description: FlightRecorders
      displayName: FlightRecorder
      kind: FlightRecorder
      name: flightrecorders.rhjmc.redhat.com
      resources:
      - kind: Deployment
        version: v1
      - kind: Service
        version: v1
      - kind: ReplicaSet
        version: v1
      - kind: Pod
        version: v1
      - kind: Secret
        version: v1
      - kind: ConfigMap
        version: v1
      specDescriptors: []
      statusDescriptors: []
      version: v1alpha1
    required: []
  description: >
    ContainerJFR provides a cloud-based solution for interacting with the
    JDK Flight Recorder already present in OpenJDK 11+ JVMs. With ContainerJFR,
    users can remotely start, stop, retrieve, and even analyze JFR event data,
    providing the capbility to easily take advantage of Flight Recorder''s
    extremely low runtime cost and overhead and the flexibility to monitor
    applications and analyze recording data without transferring data outside
    of the cluster the application runs within.
  displayName: ContainerJFR
  icon:
  - base64data: ''
    mediatype: image/png
  install:
    spec:
      clusterPermissions: []
      deployments:
      - name: container-jfr-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: container-jfr-operator
          template:
            metadata:
              labels:
                name: container-jfr-operator
            spec:
              containers:
              - command:
                - container-jfr-operator
                env:
                - name: TLS_VERIFY
                  value: 'false'
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: container-jfr-operator
                image: quay.io/rh-jmc-team/container-jfr-operator:0.3.0
                imagePullPolicy: Always
                name: container-jfr-operator
              serviceAccountName: container-jfr-operator
      permissions:
      - rules:
        - apiGroups:
          - ''
          resources:
          - pods
          - services
          - services/finalizers
          - routes
          - routes.route.openshift.io
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - container-jfr-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ''
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - rhjmc.redhat.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: container-jfr-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - flightrecorder
  - java
  - jdk
  - jfr
  - jmc
  - missioncontrol
  - monitoring
  - profiling
  labels: {}
  links:
  - name: Upstream Project
    url: https://github.com/rh-jmc-team/container-jfr
  maintainers:
  - email: aazores@redhat.com
    name: Andrew Azores
  - email: ebaron@redhat.com
    name: Elliott Baron
  maturity: pre-alpha
  minKubeVersion: ''
  provider:
    name: Red Hat
  replaces: ''
  selector:
    matchLabels: {}
  version: 0.3.0
