apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate service-serving cert for metrics
resources:
- cryostat-quickstart-jmx.yaml
- cryostat-quickstart-autoconfig.yaml
- console-plugin/clusterrolebinding-cryostat-plugin-patcher.yaml
- console-plugin/clusterrolebinding-cryostat-plugin.yaml
- console-plugin/clusterrole-cryostat-plugin-patcher.yaml
- console-plugin/clusterrole-cryostat-plugin.yaml
- console-plugin/deployment-cryostat-plugin.yaml
- console-plugin/serviceaccount-cryostat-plugin.yaml
- console-plugin/service-cryostat-plugin.yaml

patches:
- path: plugin_image_pull_patch.yaml

images:
- name: console-plugin
  newName: quay.io/cryostat/cryostat-openshift-console-plugin
  newTag: latest@sha256:0656a0c3fad2e519aa5a20de52d0a64a7f5abbe084bc08bba003199f99cc3e19
