apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryostat-plugin
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: cryostat-plugin
        imagePullPolicy: "Always"
