apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: RELATED_IMAGE_INSIGHTS_PROXY
          value: "quay.io/3scale/apicast:insights-01"
        - name: INSIGHTS_ENABLED
          value: "true"
        - name: INSIGHTS_BACKEND_DOMAIN
          value: "console.redhat.com"
