---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: insights-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: runtimes-inventory-operator
    app.kubernetes.io/part-of: runtimes-inventory-operator
    app.kubernetes.io/managed-by: kustomize
  name: insights-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: insights-role
subjects:
- kind: ServiceAccount
  name: insights
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: insights-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: runtimes-inventory-operator
    app.kubernetes.io/part-of: runtimes-inventory-operator
    app.kubernetes.io/managed-by: kustomize
  name: insights-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: insights-role
subjects:
- kind: ServiceAccount
  name: insights
