apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "rhjmc.redhat.com/v1alpha1",
          "kind": "ContainerJFR",
          "metadata": {
            "name": "containerjfr"
          },
          "spec": {
            "minimal": false
          }
        },
        {
          "apiVersion": "rhjmc.redhat.com/v1alpha2",
          "kind": "FlightRecorder",
          "metadata": {
            "name": "example-flightrecorder"
          },
          "spec": {
            "recordingSelector": {
              "matchLabels": {
                "rhjmc.redhat.com/flightrecorder": "example-flightrecorder"
              }
            }
          }
        },
        {
          "apiVersion": "rhjmc.redhat.com/v1alpha2",
          "kind": "Recording",
          "metadata": {
            "name": "example-recording"
          },
          "spec": {
            "archive": true,
            "duration": "30s",
            "eventOptions": [
              "template=ALL"
            ],
            "flightRecorder": {
              "name": "example-flightrecorder"
            },
            "name": "example-recording"
          }
        }
      ]
    capabilities: Basic Install
    categories: Monitoring, Developer Tools
    certified: "false"
    containerImage: quay.io/rh-jmc-team/container-jfr-operator:0.5.0
    createdAt: "2020-07-03 00:00:00"
    description: JVM monitoring and profiling tool
    repository: github.com/rh-jmc-team/container-jfr-operator
    support: Red Hat
  name: container-jfr-operator-bundle.v0.5.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ContainerJFR is the Schema for the containerjfrs API
      kind: ContainerJFR
      name: containerjfrs.rhjmc.redhat.com
      version: v1alpha1
    - description: FlightRecorder is the Schema for the flightrecorders API
      kind: FlightRecorder
      name: flightrecorders.rhjmc.redhat.com
      version: v1alpha2
    - description: Recording is the Schema for the recordings API
      kind: Recording
      name: recordings.rhjmc.redhat.com
      version: v1alpha2
  description: |
    ContainerJFR provides a cloud-based solution for interacting with the JDK Flight Recorder already present in OpenJDK 11+ JVMs. With ContainerJFR, users can remotely start, stop, retrieve, and even analyze JFR event data, providing the capbility to easily take advantage of Flight Recorder''s extremely low runtime cost and overhead and the flexibility to monitor applications and analyze recording data without transferring data outside of the cluster the application runs within.
  displayName: ContainerJFR
  icon:
  - base64data: ""
    mediatype: image/png
  install:
    spec:
      deployments:
      - name: container-jfr-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: container-jfr-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: container-jfr-operator
            spec:
              containers:
              - command:
                - container-jfr-operator
                env:
                - name: TLS_VERIFY
                  value: "true"
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: container-jfr-operator
                image: quay.io/rh-jmc-team/container-jfr-operator:0.5.0
                imagePullPolicy: Always
                name: container-jfr-operator
                resources: {}
              serviceAccountName: container-jfr-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - routes
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - container-jfr-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - rhjmc.redhat.com
          resources:
          - '*'
          - flightrecorders
          - recordings
          verbs:
          - '*'
        serviceAccountName: container-jfr-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - flightrecorder
  - java
  - jdk
  - jfr
  - jmc
  - missioncontrol
  - monitoring
  - profiling
  links:
  - name: Upstream Project
    url: https://github.com/rh-jmc-team/container-jfr
  maintainers:
  - email: aazores@redhat.com
    name: Andrew Azores
  - email: ebaron@redhat.com
    name: Elliott Baron
  maturity: pre-alpha
  provider:
    name: Red Hat
  replaces: container-jfr-operator-bundle.v0.4.0
  selector: {}
  version: 0.5.0
