# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/operator.cryostat.io_cryostats.yaml
- bases/operator.cryostat.io_recordings.yaml
- bases/operator.cryostat.io_flightrecorders.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_cryostats.yaml
#- patches/webhook_in_recordings.yaml
#- patches/webhook_in_flightrecorders.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_cryostats.yaml
#- patches/cainjection_in_recordings.yaml
#- patches/cainjection_in_flightrecorders.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# FIXME Remove once migrated to kubebuilder markers
patches:
- path: patches/deprecate_flightrecorders.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: flightrecorders.operator.cryostat.io
- path: patches/deprecate_recordings.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: recordings.operator.cryostat.io

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
