apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "rhjmc.redhat.com/v1beta1",
          "kind": "ContainerJFR",
          "metadata": {
            "name": "containerjfr-sample"
          },
          "spec": {
            "minimal": false,
            "trustedCertSecrets": []
          }
        },
        {
          "apiVersion": "rhjmc.redhat.com/v1beta1",
          "kind": "FlightRecorder",
          "metadata": {
            "name": "flightrecorder-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "rhjmc.redhat.com/v1beta1",
          "kind": "Recording",
          "metadata": {
            "name": "recording-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.3.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: container-jfr-operator.v1.0.0-beta1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ContainerJFR is the Schema for the containerjfrs API
      displayName: Container JFR
      kind: ContainerJFR
      name: containerjfrs.rhjmc.redhat.com
      version: v1beta1
    - description: FlightRecorder is the Schema for the flightrecorders API
      displayName: Flight Recorder
      kind: FlightRecorder
      name: flightrecorders.rhjmc.redhat.com
      version: v1beta1
    - description: Recording is the Schema for the recordings API
      displayName: Recording
      kind: Recording
      name: recordings.rhjmc.redhat.com
      version: v1beta1
  description: Some description text
  displayName: ContainerJFR Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: container-jfr-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                image: quay.io/andrewazores/container-jfr-operator:1.0.0-beta1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsUser: 65532
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          - coordination.k8s.io
          resources:
          - configmaps
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - jfr
  - jdk
  links:
  - name: Container Jfr Operator
    url: https://container-jfr-operator.domain
  maintainers:
  - email: aazores@redhat.com
    name: Andrew Azores
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 1.0.0-beta1
