name: Clean up PR-scoped test images

on:
  pull_request_target:
    types:
      - closed

jobs:
  delete-images:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.repository_owner == 'cryostatio'
    strategy:
      matrix:
        image: [cryostat-operator, cryostat-operator-bundle, cryostat-operator-scorecard]
    steps:
    - uses: r26d/ghcr-delete-image-action@v1.3.0
      with:
        owner: ${{ github.repository_owner }}
        name: ${{ matrix.image }}
        token: ${{ secrets.GITHUB_TOKEN }}
        ignore-missing-package: true
        tag-regex: pr-${{ github.event.number }}-.*
        tagged-keep-latest: 0
