on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      repository:
        required: false
        type: string
      ref:
        required: false
        type: string
      sha:
        required: true
        type: string
      
env:
  OPENSUSE_UNOFFICIAL_LIBCONTAINERS_KEY_URL: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/Release.key"
  OPENSUSE_UNOFFICIAL_LIBCONTAINERS_SOURCE_URL: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04"

permissions:
  statuses: write

jobs:
  controller-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: '1.25.*'
    - name: Run controller tests
      run: make test-envtest
    - name: Set latest commit status as ${{ job.status }}
      uses: daltonbr/set-commit-status-action@2a09190f6d04d912bca5ede8094b5d5dce303ebb # v3.0.1
      if: always()
      with:
        sha: ${{ inputs.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        context: ${{ github.job }}
  
  scorecard-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
    - name: Build scorecard image for test
      run: |
        CUSTOM_SCORECARD_IMG=localhost:5000/${{ github.repository_owner }}/cryostat-operator-scorecard:${{ inputs.tag }} \
        PLATFORMS=linux/amd64 \
        MANIFEST_PUSH=false \
        make scorecard-build
    - name: Build operator image for test
      run: |
        OPERATOR_IMG=localhost:5000/${{ github.repository_owner }}/cryostat-operator:${{ inputs.tag }} \
        SKIP_TESTS=true \
        make oci-build
    - name: Build bundle image for test
      run: |
        OPERATOR_IMG=localhost:5000/${{ github.repository_owner }}/cryostat-operator:${{ inputs.tag }} \
        BUNDLE_IMG=localhost:5000/${{ github.repository_owner }}/cryostat-operator-bundle:${{ inputs.tag }} \
        make bundle bundle-build
    - name: Set up Kind cluster
      uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
      with:
        config: .github/kind-config.yaml
        cluster_name: ci-${{ github.run_id }}
        wait: 1m
        ignore_failed_clean: true
    - name: Set up local image registry
      run: make scorecard-kind-registry SCORECARD_KIND_CLUSTER=ci-${{ github.run_id }} KIND_RUNTIME=docker
    - name: Install cluster prerequisites (OLM, cert-manager, ingress-nginx)
      run: make scorecard-kind-prereqs
    - name: Push test images to local registry
      run: |
        make scorecard-kind-push SCORECARD_PUSH_IMAGES="localhost:5000/${{ github.repository_owner }}/cryostat-operator-scorecard:${{ inputs.tag }} localhost:5000/${{ github.repository_owner }}/cryostat-operator:${{ inputs.tag }} localhost:5000/${{ github.repository_owner }}/cryostat-operator-bundle:${{ inputs.tag }}"
    - name: Run scorecard tests
      run: |
        BUNDLE_IMG="localhost:5000/${{ github.repository_owner }}/cryostat-operator-bundle:${{ inputs.tag }}" \
        SCORECARD_BUNDLE="./bundle" \
        RUN_BUNDLE_EXTRA_ARGS="--use-http --skip-tls" \
        make test-scorecard
    - name: Set latest commit status as ${{ job.status }}
      uses: daltonbr/set-commit-status-action@2a09190f6d04d912bca5ede8094b5d5dce303ebb # v3.0.1
      if: always()
      with:
        sha: ${{ inputs.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        context: ${{ github.job }}
