name: test-CI-on-push

concurrency:
  group: ci-${{ github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  get-test-image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.compute-tag.outputs.tag }}
    steps:
    - name: Compute test image tag
      id: compute-tag
      run: |
        prefix="ci"
        if [ -n "${{ github.event.number }}" ]; then
          prefix="pr-${{ github.event.number }}"
        fi
        echo "tag=${prefix}-$GITHUB_SHA" >> $GITHUB_OUTPUT
  
  run-test-jobs:
    uses: ./.github/workflows/test-ci-reusable.yml
    needs: [get-test-image-tag]
    with:
      tag: ${{ needs.get-test-image-tag.outputs.tag }}
